<template>
  <div>
    <navigation/>
    <section class="hero pa3 pa5-m pa5-l pa5-ns cf bb">
      <div class="fl w-100 w-100-m w-60-l w-60-ns">
        <h1 class="f3 f2-m f2-l f2-ns mt0 pt3">Front-end Developer, Drupal &amp; WordPress</h1>
        <p class="f4 f3-m f3-l f3-ns measure lh-copy">
          I build websites with Drupal, WordPress, Grav, and a variety of other great open source software. I design HTML5 themes and
          templates with Sass and Less, and use Gulp as my task runner.
        </p>
        <p class="f4 f3-m f3-l f3-ns measure lh-copy">
          Right now I'm focusing on learning Vue.js and brushing up on my Laravel skills.
        </p>
        <p class="f4 f3-m f3-l f3-ns measure lh-copy">I currently work for the publishing services firm Scribe Inc.</p>
        </p>
      </div>
    </section>
    <section class="project pa3 pa5-m pa5-l pa5-ns cf bb">
      <h1 class="f3 f2-m f2-l f2-ns mt0 pt3">Recent Projects</h1>
      <p class="f4 f3-m f3-l f3-ns measure lh-copy mb5">
          I build websites with Drupal, WordPress, Grav, and a variety of other great open source software. I design HTML5 themes and
          templates with Sass and Less, and use Gulp as my task runner.
        </p>
        <div class="fl w-100 w-100-m w-25-l w-25-ns pr4">
          <nuxt-link to="/projects/gifford"><img src="~/assets/img/gifford-lectures-phone.png" v-scroll-reveal.reset></nuxt-link>
          </div>
        <div class="fl w-100 w-100-m w-25-l w-25-ns pr4">
          <img src="~/assets/img/acculturated-phone.png" v-scroll-reveal.reset> 
            </div>
        <div class="fl w-100 w-100-m w-25-l w-25-ns pr4">
          <img src="~/assets/img/csm-phone.png" v-scroll-reveal.reset>
           </div>
        <div class="fl w-100 w-100-m w-25-l w-25-ns">
          <img src="https://www.algolia.com/static_assets/images/svg/screens/screen-digitalocean-tablet-34841f11.svg" v-scroll-reveal.reset>          </div>
      
    </section>

    <section class="promote">

    </section>
  </div>
</template>



<script>
  import Navigation from '~/components/Navigation.vue'

  export default {
    components: {
      Navigation
    }
  }
</script>

<style lang="scss" scoped>

@import "~assets/scss/_variables.scss";
.hero {
  color: $white;
  background-color: #306ffd;
  background-image: linear-gradient(60deg,#306efe,#003ab7);
  font-family: $avenir;
}

.project {

  background: $gray-lighter;
  font-family: $avenir;
  img {
    box-shadow: rgba(112,128,175,0.2) 0 -16px 24px;

  }
}

.promote {
  background: $white;
  position: relative;
    padding-top: 0;

  &:before {
    
    content: '';
    display: block;
    position: absolute;
    width: 100%;
    height: 350px;
    background: white;
    -ms-transform: skewY(-6deg);
    transform: skewY(-6deg);
    z-index: 0;
    top: -170px;
    z-index: 1;
    box-shadow: rgba(112,128,175,0.2) 0 -16px 24px;

}
  }

.project--image {
  background: $gray;

}
.slide-in-left {
  -webkit-animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  animation: slide-in-left 0.5s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}
/* ----------------------------------------------
 * Generated by Animista on 2017-9-28 15:20:28
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slide-in-left
 * ----------------------------------------
 */
@-webkit-keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}
@keyframes slide-in-left {
  0% {
    -webkit-transform: translateX(-1000px);
    transform: translateX(-1000px);
    opacity: 0;
  }
  100% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
}

</style>
